# Используем официальный образ Node.js
FROM node:22.12.0-alpine AS production

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Собираем проект
RUN npm run build --prod

# Используем официальный образ Nginx для сервировки статики
FROM nginx:alpine

# Копируем собранные файлы из предыдущего этапа
COPY --from=build /app/dist/cs2-cases-frontend/browser /usr/share/nginx/html/cs2-cases-frontend

# Копируем конфигурацию Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт, на котором будет работать приложение
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]
